const std = @import("std");
const Chat = @import("Chat.zig").Chat;
const User = @import("User.zig").User;
const MessageOrigin = @import("MessageOrigin.zig").MessageOrigin;
const MessageEntity = @import("MessageEntity.zig").MessageEntity;
const ExternalReplyInfo = @import("ExternalReplyInfo.zig").ExternalReplyInfo;
const TextQuote = @import("TextQuote.zig").TextQuote;
const Story = @import("Story.zig").Story;
const Animation = @import("Animation.zig").Animation;
const Audio = @import("Audio.zig").Audio;
const Document = @import("Document.zig").Document;
const PaidMediaInfo = @import("PaidMediaInfo.zig").PaidMediaInfo;
const PhotoSize = @import("PhotoSize.zig").PhotoSize;
const Sticker = @import("Sticker.zig").Sticker;
const Video = @import("Video.zig").Video;
const VideoNote = @import("VideoNote.zig").VideoNote;
const Voice = @import("Voice.zig").Voice;
const Contact = @import("Contact.zig").Contact;
const Dice = @import("Dice.zig").Dice;
const Game = @import("Game.zig").Game;
const Poll = @import("Poll.zig").Poll;
const Venue = @import("Venue.zig").Venue;
const Location = @import("Location.zig").Location;
const InlineKeyboardMarkup = @import("keyboard/InlineKeyboardMarkup.zig").InlineKeyboardMarkup;
const WebAppData = @import("WebAppData.zig").WebAppData;
const ForumTopicClosed = @import("ForumTopicClosed.zig").ForumTopicClosed;
const LinkPreviewOptions = @import("LinkPreviewOptions.zig").LinkPreviewOptions;
const MessageAutoDeleteTimerChanged = @import("MessageAutoDeleteTimerChanged.zig").MessageAutoDeleteTimerChanged;
const ChatBoostAdded = @import("ChatBoostAdded.zig").ChatBoostAdded;
const ChatBackground = @import("ChatBackground.zig").ChatBackground;
const ChatShared = @import("ChatShared.zig").ChatShared;
const ForumTopicCreated = @import("ForumTopicCreated.zig").ForumTopicCreated;
const ForumTopicEdited = @import("ForumTopicEdited.zig").ForumTopicEdited;
const ForumTopicReopened = @import("ForumTopicReopened.zig").ForumTopicReopened;
const GeneralForumTopicHidden = @import("GeneralForumTopicHidden.zig").GeneralForumTopicHidden;
const GeneralForumTopicUnhidden = @import("GeneralForumTopicUnhidden.zig").GeneralForumTopicUnhidden;
const GiveawayCreated = @import("GiveawayCreated.zig").GiveawayCreated;
const Giveaway = @import("Giveaway.zig").Giveaway;
const MaybeInaccessibleMessage = @import("MaybeInaccessibleMessage.zig").MaybeInaccessibleMessage;
const GiveawayWinners = @import("GiveawayWinners.zig").GiveawayWinners;
const GiveawayCompleted = @import("GiveawayCompleted.zig").GiveawayCompleted;
const ProximityAlertTriggered = @import("ProximityAlertTriggered.zig").ProximityAlertTriggered;
const RefundedPayment = @import("RefundedPayment.zig").RefundedPayment;
const SuccessfulPayment = @import("SuccessfulPayment.zig").SuccessfulPayment;
const UsersShared = @import("UsersShared.zig").UsersShared;
const Invoice = @import("Invoice.zig").Invoice;
const WriteAccessAllowed = @import("WriteAccessAllowed.zig").WriteAccessAllowed;
const PassportData = @import("PassportData.zig").PassportData;
const VideoChatScheduled = @import("VideoChatScheduled.zig").VideoChatScheduled;
const VideoChatStarted = @import("VideoChatStarted.zig").VideoChatStarted;
const VideoChatEnded = @import("VideoChatEnded.zig").VideoChatEnded;
const VideoChatParticipantsInvited = @import("VideoChatParticipantsInvited.zig").VideoChatParticipantsInvited;

pub const Message = struct {
    message_id: i64,
    message_thread_id: ?i64 = null,
    from: ?User = null,
    sender_chat: ?Chat = null,
    sender_boost_count: ?i32 = null,
    sender_business_bot: ?User = null,
    date: i32,
    business_connection_id: ?[]const u8 = null,
    chat: Chat,
    forward_origin: ?MessageOrigin = null,
    is_topic_message: ?bool = null,
    is_automatic_forward: ?bool = null,
    reply_to_message: ?*Message = null,
    external_reply: ?ExternalReplyInfo = null,
    quote: ?TextQuote = null,
    reply_to_story: ?Story = null,
    via_bot: ?User = null,
    edit_date: ?i32 = null,
    has_protected_content: ?bool = null,
    is_from_offline: ?bool = null,
    media_group_id: ?[]const u8 = null,
    author_signature: ?[]const u8 = null,
    text: ?[]const u8 = null,
    entities: ?[]MessageEntity = null,
    link_preview_options: ?LinkPreviewOptions = null,
    effect_id: ?[]const u8 = null,
    animation: ?Animation = null,
    audio: ?Audio = null,
    document: ?Document = null,
    paid_media: ?PaidMediaInfo = null,
    photo: ?[]PhotoSize = null,
    sticker: ?Sticker = null,
    story: ?Story = null,
    video: ?Video = null,
    video_note: ?VideoNote = null,
    voice: ?Voice = null,
    caption: ?[]const u8 = null,
    caption_entities: ?[]MessageEntity = null,
    show_caption_above_media: ?bool = null,
    has_media_spoiler: ?bool = null,
    contact: ?Contact = null,
    dice: ?Dice = null,
    game: ?Game = null,
    poll: ?Poll = null,
    venue: ?Venue = null,
    location: ?Location = null,
    new_chat_members: ?[]User = null,
    left_chat_member: ?User = null,
    new_chat_title: ?[]const u8 = null,
    new_chat_photo: ?[]PhotoSize = null,
    delete_chat_photo: ?bool = null,
    group_chat_created: ?bool = null,
    supergroup_chat_created: ?bool = null,
    channel_chat_created: ?bool = null,
    message_auto_delete_timer_changed: ?MessageAutoDeleteTimerChanged = null,
    migrate_to_chat_id: ?i64 = null,
    migrate_from_chat_id: ?i64 = null,
    pinned_message: ?MaybeInaccessibleMessage = null,
    invoice: ?Invoice = null,
    successful_payment: ?SuccessfulPayment = null,
    refunded_payment: ?RefundedPayment = null,
    users_shared: ?UsersShared = null,
    chat_shared: ?ChatShared = null,
    connected_website: ?[]const u8 = null,
    write_access_allowed: ?WriteAccessAllowed = null,
    passport_data: ?PassportData = null,
    proximity_alert_triggered: ?ProximityAlertTriggered = null,
    boost_added: ?ChatBoostAdded = null,
    chat_background_set: ?ChatBackground = null,
    forum_topic_created: ?ForumTopicCreated = null,
    forum_topic_edited: ?ForumTopicEdited = null,
    forum_topic_closed: ?ForumTopicClosed = null,
    forum_topic_reopened: ?ForumTopicReopened = null,
    general_forum_topic_hidden: ?GeneralForumTopicHidden = null,
    general_forum_topic_unhidden: ?GeneralForumTopicUnhidden = null,
    giveaway_created: ?GiveawayCreated = null,
    giveaway: ?Giveaway = null,
    giveaway_winners: ?GiveawayWinners = null,
    giveaway_completed: ?GiveawayCompleted = null,
    video_chat_scheduled: ?VideoChatScheduled = null,
    video_chat_started: ?VideoChatStarted = null,
    video_chat_ended: ?VideoChatEnded = null,
    video_chat_participants_invited: ?VideoChatParticipantsInvited = null,
    web_app_data: ?WebAppData = null,
    reply_markup: ?InlineKeyboardMarkup = null,
    forward_from: ?User = null,
    forward_date: ?i32 = null,
};
